name: bash
on:
  schedule:
  - cron: '*/30 * * * *'
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
#    - name: 'update'
#      run: sudo apt update && docker version
    - name: 'login'
      run: skopeo login -u ${{ secrets.REGISTERY_USERNAME }} registry.cn-hangzhou.aliyuncs.com -p "${{ secrets.REGISTERY_PASSWORD }}"
    - name: sync
      run: python sync.py -v

